FROM golang:latest as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ENV CGO_ENABLED=0
RUN go build -o main .

FROM gcr.io/distroless/base-debian11
COPY --from=builder /app/main .
COPY .env .  
EXPOSE 5555
CMD ["/main"]
